name: knot-space
description: Online repository server for Knot packages
build: "cargo build --release"

# Server-specific scripts
scripts:
  dev: "cargo run"
  test: "cargo test"
  check: "cargo check"
  lint: "cargo clippy -- -D warnings"
  fmt: "cargo fmt"
  fmt-check: "cargo fmt -- --check"
  build-debug: "cargo build"
  build-release: "cargo build --release"
  clean: "cargo clean"
  doc: "cargo doc --open"
  serve: "cargo run --release"
  watch: "cargo watch -x run"
  integration-test: "cargo test --test '*'"
  load-test: "echo 'Load testing not implemented yet'"
  docker-build: "docker build -t knot-space ."
  docker-run: "docker run -p 8000:8000 knot-space"