[build]
target = "bun"
outdir = "./dist"

[build.external]
packages = ["@prisma/client"]

[build.define]
"process.env.NODE_ENV" = '"production"'

[tsconfig-paths]
baseUrl = "."
paths = { "@/*" = ["./src/*"] }