# Bun configuration file

# Path aliases configuration - comprehensive mapping
[alias]
"@" = "./src/lib"
"@/*" = "./src/lib/*"
"@/modules" = "./src/modules"
"@/modules/*" = "./src/modules/*"  
"@/types" = "./src/types"
"@/types/*" = "./src/types/*"

[install]
# Install configuration
peer = true