# Bun configuration file

# Path aliases configuration matching tsconfig.json
[alias]
"@/*" = "./src/*"
"@/lib/*" = "./src/lib/*"
"@/modules/*" = "./src/modules/*"
"@/types/*" = "./src/types/*"

[install]
# Install configuration
peer = true