name: ui-components
description: Reusable UI components for CasaEats
team: frontend-team
version: 2.1.0

scripts:
  build: "tsc && rollup -c"
  dev: "storybook dev -p 6007"
  test: "vitest run"
  test-watch: "vitest watch"
  lint: "eslint src/ --ext .ts,.tsx"
  format: "prettier --write src/"
  build-storybook: "storybook build -o storybook-static"