name: frontend
description: React frontend application with TypeScript
tsAlias: "@"  # Override project setting
build: "vite build"

scripts:
  dev: "vite dev --port 3000"
  preview: "vite preview"
  test: "vitest run"
  test-ui: "vitest --ui"
  test-watch: "vitest watch"
  lint: "eslint src/ --ext .ts,.tsx"
  format: "prettier --write src/"
  storybook: "storybook dev -p 6006"
  build-storybook: "storybook build"

packages:
  - types
  - validators
  - ui-components
