name: logger
description: Advanced logging utility with multiple outputs and filtering
team: infrastructure-team
version: 3.2.1

# Tags for better discoverability
tags:
  - logging
  - utilities
  - typescript
  - debugging
  - monitoring
  - console
  - json

scripts:
  build: "tsc && rollup -c rollup.config.js"
  dev: "tsc --watch"
  test: "vitest run --coverage"
  test-watch: "vitest watch"
  lint: "eslint src/ --ext .ts,.js"
  format: "prettier --write src/"
  docs: "typedoc --out docs src/"
  benchmark: "node benchmarks/performance.js"
  example: "ts-node examples/basic-usage.ts"
