name: api-client
version: 1.2.0
description: HTTP client wrapper with authentication and caching
author: saravenpi
license: MIT

dependencies:
  - utils  # Will use alias to import utilities

scripts:
  build: "tsc"
  test: "jest"
  dev: "tsc --watch"

exports:
  ".": "./src/index.ts"
  "./auth": "./src/auth.ts"
  "./interceptors": "./src/interceptors.ts"