name: knot-space-ui
description: Frontend UI for Knot Space package registry
build: "npm run build"

# Frontend-specific scripts
scripts:
  dev: "npm run dev"
  build: "npm run build"
  preview: "npm run preview"
  check: "npm run check"
  lint: "npm run lint"
  format: "npm run format"
  install: "npm install"
  clean: "rm -rf .svelte-kit build node_modules"
  type-check: "npm run check"
