name: analytics
description: Analytics app showcasing $ alias usage
tsAlias: "$"  # Short, unique alias for analytics

packages:
  - utils
  - data-layer
  - @saravenpi/charts@latest

scripts:
  build: "webpack --mode=production"
  dev: "webpack serve --mode=development"
  test: "jest"
  analyze: "webpack-bundle-analyzer dist/bundle.js"