name: validators
description: Input validation and schema validation utilities
team: platform-team  
version: 2.0.1

scripts:
  build: "tsc && rollup -c"
  test: "vitest run --coverage"
  test-watch: "vitest watch"
  lint: "eslint src/ --ext .ts"
  format: "prettier --write src/"
  benchmark: "node benchmarks/validate-performance.js"