name: backend
description: Node.js API server with Express and TypeScript
tsAlias: "#"  # Override project setting
build: "tsc && node dist/index.js"

scripts:
  dev: "nodemon --exec ts-node src/index.ts"
  test: "jest --coverage"
  test-watch: "jest --watch"
  lint: "eslint src/ --ext .ts,.js"
  format: "prettier --write src/"
  db-migrate: "npm run typeorm migration:run"
  db-seed: "ts-node scripts/seed.ts"

packages:
  - types
  - validators  
  - "@jwt"
  - "@klysium/logger"
  - "@modules-loader"
