name: mobile-app
description: Mobile app using global # alias (inherited)
# No tsAlias specified - inherits global "#" from knot.yml

packages:
  - ui-components
  - utils
  - @saravenpi/mobile-utils@^1.0.0

scripts:
  build: "expo build"
  dev: "expo start"
  test: "jest"
  ios: "expo start --ios"
  android: "expo start --android"