name: knot-cli
description: The Knot CLI tool for monorepo package management
build: "cargo build --release"

# CLI-specific scripts
scripts:
  dev: "cargo run"
  test: "cargo test"
  check: "cargo check"
  lint: "cargo clippy -- -D warnings"
  fmt: "cargo fmt"
  fmt-check: "cargo fmt -- --check"
  build-debug: "cargo build"
  build-release: "cargo build --release"
  install: "cargo build --release && sudo cp target/release/knot /usr/local/bin/"
  clean: "cargo clean"
  doc: "cargo doc --open"
  benchmark: "cargo bench"