name: knot-cli
description: The Knot CLI tool for monorepo package management
tsAlias: null
packages:
- utils
- '@jwt'
build: cargo build --release
scripts:
  dev: cargo run
  fmt-check: cargo fmt -- --check
  build-release: cargo build --release
  doc: cargo doc --open
  build-debug: cargo build
  test: cargo test
  benchmark: cargo bench
  lint: cargo clippy -- -D warnings
  check: cargo check
  clean: cargo clean
  install: cargo build --release && sudo cp target/release/knot /usr/local/bin/
  fmt: cargo fmt
