name: data-layer
version: 1.5.0
description: Data access layer with caching and validation
author: saravenpi
license: MIT

dependencies:
  - utils  # Uses alias system to import utilities
  - api-client  # Another local package dependency

scripts:
  build: "tsc"
  test: "jest"
  lint: "eslint src/"

exports:
  ".": "./src/index.ts"
  "./cache": "./src/cache.ts"
  "./validators": "./src/validators.ts"
  "./repository": "./src/repository.ts"