name: utils
version: 1.0.0
description: Common utility functions used across all apps
author: saravenpi
license: MIT

scripts:
  build: "bun run build"
  test: "bun test"
  dev: "bun run dev"

dependencies:
  - lodash@^4.17.21

exports:
  ".": "./src/index.ts"
  "./strings": "./src/strings.ts"
  "./dates": "./src/dates.ts"
  "./validation": "./src/validation.ts"